init_db: true
period: 1
port: 7788
packet_name_space: TEST
packets:
  1:
    name:     Test01_B
    version:  1.0
    cell_csv: public/files/test01_B.csv
  2:
    name:     Test01_U
    version:  1.0
    cell_csv: public/files/test01_U.csv
  3:
    name:     Test01_S
    version:  1.0
    cell_csv: public/files/test01_S.csv
  4:
    name:     Test01_F
    version:  1.0
    cell_csv: public/files/test01_F.csv
  5:
    name:     Test01
    version:  1.0
    cell_csv: public/files/test01.csv
  6:
    name:     Test02
    version:  1.0
    cell_csv: public/files/test02.csv
  7:
    name:     Test03
    version:  1.0
    cell_csv: public/files/test03.csv

